Noc_App/Models/ViewModel/GrantViewModel.cs
namespace Noc_App.Models.ViewModel
{
    public class GrantViewModel
    {
        public int Id { get; set; }
        public string ApplicationID { get; set; }
        public string OrderId { get; set; }
        public string Message { get; set; }
        public double TotalAmount { get; set; }
        public bool IsUnderMasterPlan { get; set; }
    }
}

Noc_App/Controllers/GrantController.cs
using Microsoft.AspNetCore.Mvc;
using Noc_App.Models.interfaces;
using Noc_App.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Noc_App.Models.ViewModel;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Noc_App.Helpers;
using Noc_App.UtilityService;
using Noc_App.Models.Payment;
using Rotativa.AspNetCore;
using System.Collections.Generic;
using System.Security.Cryptography;
using Noc_App.Clients;
using System.Globalization;
using Newtonsoft.Json;
using System.Reflection.Metadata.Ecma335;
using System.Diagnostics.Eventing.Reader;
using Noc_App.PaymentUtilities;
using static Noc_App.Models.IFMSPayment.DepartmentModel;
using System.Text;
using System.Net;
using Noc_App.Models.IFMSPayment;
using Org.BouncyCastle.Asn1.Ocsp;

namespace Noc_App.Controllers
{
    public class GrantController : Controller
    {
        private readonly IRepository<GrantDetails> _repo;
        //private readonly IRepository<VillageDetails> _villageRpo;
        private readonly IRepository<TehsilBlockDetails> _tehsilBlockRepo;
        private readonly IRepository<SubDivisionDetails> _subDivisionRepo;
        private readonly IRepository<DivisionDetails> _divisionRepo;
        private readonly IRepository<ProjectTypeDetails> _projectTypeRepo;
        private readonly IRepository<NocPermissionTypeDetails> _nocPermissionTypeRepo;
        private readonly IRepository<NocTypeDetails> _nocTypeRepo;
        private readonly IRepository<OwnerTypeDetails> _ownerTypeRepo;
        private readonly IRepository<GrantKhasraDetails> _khasraRepo;
        private readonly IRepository<SiteAreaUnitDetails> _siteUnitsRepo;
        private readonly IRepository<GrantPaymentDetails> _grantPaymentRepo;
        private readonly IRepository<OwnerDetails> _grantOwnersRepo;
        private readonly IRepository<GrantApprovalDetail> _repoApprovalDetail;
        private readonly IRepository<SiteUnitMaster> _repoSiteUnitMaster;
        private readonly IEmailService _emailService;
        private readonly ICalculations _calculations;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IRepository<DistrictDetails> _districtRepo;
        private readonly IRepository<GrantRejectionShortfallSection> _grantrejectionRepository;
        private readonly IRepository<GrantSectionsDetails> _grantsectionRepository;
        private readonly IRepository<GrantApprovalMaster> _repoApprovalMaster;
        private readonly IRepository<DaysCheckMaster> _repoDaysCheckMaster;
        private readonly IRepository<PlanSanctionAuthorityMaster> _repoPlanSanctionAuthtoryMaster;
        private readonly IRepository<MasterPlanDetails> _masterPlanDetailsRepository;
        private readonly IRepository<ChallanDetails> _repoChallanDetails;
        private readonly IConfiguration _configuration;
        private readonly IRepository<GrantPaymentDetails> _repoPayment;
        private readonly IRepository<GrantApprovalProcessDocumentsDetails> _repoApprovalDocument;

        [Obsolete]
        private readonly IHostingEnvironment _hostingEnvironment;
        [Obsolete]
        public GrantController(IRepository<GrantDetails> repo, /*IRepository<VillageDetails> villageRepo,*/ IRepository<TehsilBlockDetails> tehsilBlockRepo, IRepository<SubDivisionDetails> subDivisionRepo,
            IRepository<DivisionDetails> divisionRepo, IRepository<ProjectTypeDetails> projectTypeRepo, IRepository<NocPermissionTypeDetails> nocPermissionTypeRepo,
            IRepository<NocTypeDetails> nocTypeRepo, IRepository<OwnerTypeDetails> ownerTypeRepo, IHostingEnvironment hostingEnvironment, IRepository<GrantApprovalProcessDocumentsDetails> repoApprovalDocument,
            IRepository<GrantKhasraDetails> khasraRepo, IRepository<SiteAreaUnitDetails> siteUnitsRepo, IEmailService emailService, IConfiguration configuration,
            IRepository<GrantPaymentDetails> grantPaymentRepo, IRepository<OwnerDetails> grantOwnersRepo, IRepository<DistrictDetails> districtRepo,
            IRepository<GrantApprovalDetail> repoApprovalDetail, IWebHostEnvironment hostEnvironment, IRepository<SiteUnitMaster> repoSiteUnitMaster
            , ICalculations calculations, IRepository<GrantRejectionShortfallSection> grantrejectionRepository, IRepository<MasterPlanDetails> masterPlanDetailsRepository
            , IRepository<GrantSectionsDetails> grantsectionRepository, IRepository<GrantApprovalMaster> repoApprovalMaster, IRepository<ChallanDetails> repoChallanDetails
            , IRepository<DaysCheckMaster> repoDaysCheckMaster, IRepository<PlanSanctionAuthorityMaster> repoPlanSanctionAuthtoryMaster, IRepository<GrantPaymentDetails> repoPayment)
        {
            //_villageRpo = villageRepo;
            _tehsilBlockRepo = tehsilBlockRepo;
            _subDivisionRepo = subDivisionRepo;
            _divisionRepo = divisionRepo;
            _projectTypeRepo = projectTypeRepo;
            _nocPermissionTypeRepo = nocPermissionTypeRepo;
            _nocTypeRepo = nocTypeRepo;
            _ownerTypeRepo = ownerTypeRepo;
            _hostingEnvironment = hostingEnvironment;
            _repo = repo;
            _emailService = emailService;
            _khasraRepo = khasraRepo;
            _siteUnitsRepo = siteUnitsRepo;
            _grantPaymentRepo = grantPaymentRepo;
            _grantOwnersRepo = grantOwnersRepo;
            _repoApprovalDetail = repoApprovalDetail;
            _hostEnvironment = hostEnvironment;
            _repoSiteUnitMaster = repoSiteUnitMaster;
            _calculations = calculations;
            _districtRepo = districtRepo;
            _grantrejectionRepository = grantrejectionRepository;
            _grantsectionRepository = grantsectionRepository;
            _repoApprovalMaster = repoApprovalMaster;
            _repoDaysCheckMaster = repoDaysCheckMaster;
            _repoPlanSanctionAuthtoryMaster = repoPlanSanctionAuthtoryMaster;
            _masterPlanDetailsRepository = masterPlanDetailsRepository;
            _repoChallanDetails = repoChallanDetails;
            _configuration = configuration;
            _repoPayment = repoPayment;
            _repoApprovalDocument = repoApprovalDocument;
        }

        [AllowAnonymous]
        public ViewResult Index(string Id)
        {
            try
            {
                var g = (from gr in _repo.GetAll()
                         join p in _grantPaymentRepo.GetAll() on gr.Id equals p.GrantID into payment
                         from pay in payment.DefaultIfEmpty()
                         where gr.ApplicationID.ToLower() == Id.Trim().ToLower()
                         select new
                         {
                             gr,
                             pay

                         }
                    ).FirstOrDefault();
                GrantDetails obj = g.gr;
                if (g.gr.IsUnderMasterPlan)
                {
                    GrantViewModel model = new GrantViewModel
                    {
                        Id = obj.Id,
                        ApplicationID = obj.ApplicationID,
                        OrderId = "0",
                        Message = "Payment is not successfull",
                        TotalAmount = 0,
                        IsUnderMasterPlan=true
                    };
                    return View(model);
                }
                else
                {
                    double total = 0;
                    var units = _repoSiteUnitMaster.Find(x => x.SiteAreaUnitId == g.gr.SiteAreaUnitId);
                    SiteUnitMaster k = units.Where(x => x.UnitCode.ToUpper() == "K").FirstOrDefault();
                    SiteUnitMaster m = units.Where(x => x.UnitCode.ToUpper() == "M").FirstOrDefault();
                    SiteUnitMaster s = units.Where(x => x.UnitCode.ToUpper() == "S").FirstOrDefault();
                    total = Math.Round(((from kh in _khasraRepo.GetAll()
                                         where kh.GrantID == g.gr.Id
                                         select new
                                         {
                                             TotalArea = ((kh.KanalOrBigha * k.UnitValue * k.Timesof) / k.DivideBy) + ((kh.MarlaOrBiswa * m.UnitValue * m.Timesof) / m.DivideBy) + ((kh.SarsaiOrBiswansi * s.UnitValue * s.Timesof) / s.DivideBy)

                                         }).Sum(d => d.TotalArea)), 5);
                    double TotalPayment = 0;
                    //string calculation = "";


                    if (obj != null)
                    {
                        var payment = g.pay;
                        if (payment == null)
                        {
                            GrantViewModel model = new GrantViewModel
                            {
                                Id = obj.Id,
                                ApplicationID = obj.ApplicationID,
                                OrderId = "0",
                                Message = "Payment is not successfull",
                                TotalAmount = TotalPayment,
                                IsUnderMasterPlan = false
                            };
                            return View(model);
                        }
                        else
                        {
                            if (Convert.ToDouble(total) <= 0.50)
                            {
                                TotalPayment = 500;
                                //calculation = "For " + total.ToString() + " Acre, Amount is " + TotalPayment.ToString();
                            }
                            else if (Convert.ToDouble(total) > 0.50 && Convert.ToDouble(total) <= 1)
                            {
                                TotalPayment = 1000;
                                //calculation = "For " + total.ToString() + " Acre, Amount is " + TotalPayment.ToString();
                            }

Noc_App/Views/Grant/Expired.cshtml
@{
    ViewData["Title"] = "Expired....";
    Layout = "~/Views/Shared/_LayoutWithoutLinks.cshtml";
}



                <div class="section-title">
                    <h2>Link Expired</h2>
                </div>

                <div class="row">

                    <div class="col-lg-12 mt-5 mt-lg-0 d-flex align-items-stretch">
                        <div class="card shadow mb-4 col-lg-12">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="card-header py-3">
                                        <h2 class="m-0 font-weight-bold text-danger">Expired....</h2>
                                    </div>
                                    <div class="card-body">
                                            <div class="row col-md-12">
                                                <strong>
                                                    <label name="message" class="control-label">You can not modify application due to expired link</label>
                                                </strong>
                                                <div class="">
                                                    <div class="col-lg-12" style="text-align:center">
                                                        <a class="btn btn-secondary btn-user btn-block" asp-controller="Grant" asp-action="Create">Back</a>
                                                    </div>
                                                </div>
                                            </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            

Noc_App/Views/Grant/FailureUrl.cshtml
@* @{
    ViewBag.Title = "Failed";
    Layout = "";
    TempData["Message"] = ViewBag.HtmlContent;
    ViewBag.HtmlContent = TempData["Message"];
}
<div asp-validation-summary="All" class="text-danger"></div>

<div>

    @Html.Raw(ViewBag.HtmlContent)

</div> *@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
        <meta name='ContentType' content='application/json' /><meta name='Accept' content='application/json' />
    <title>Payu - IFMS Api</title>
    <style>
        body {
            overflow-x: hidden;
        }
    </style>
</head>
<body>
    <main role="main">
            <form id="PostForm" name="PostForm" action="http://localhost:5126/Payment/failureURL" method="POST"><input type='hidden' name='encData' value='' />
                <input type='hidden' name='clientId' value='3dad2e78100f42ec999abb423f193333' /><input type='hidden' name='clientSecret' value='6abcc8627e34498abb4bc7c562603333' />
                <input type='hidden' name='integratingAgency' value='DUAT01' />
                <input type='hidden' name='ipAddress' value='103.118.160.57,52.172.29.171,52.172.35.118,10.43.19.41,192.168.5.133,112.196.25.180,52.172.29.171,14.139.239.253,10.43.19.41' />
                <input type='hidden' name='deptRefNo' value='202407111611135882' /><input type='hidden' name='DeptCode' value='WAS' /><input type='hidden' name='statusCode' value='EC307' />
                <input type='hidden' name='msg' value='' />
                <h1>Something wrong has happend! Payment is not successful</h1>
            </form>

</main>

<footer class="footer text-muted">
    <div class="container" style="
    text-align: center;
    color: white;
">
        © Copyright IFMS-2020. All Rights Reserved<br />
        Designed and Developed by NIC PUNJAB
    </div>
    </div>
</footer>
<script src="https://ifmstg.punjab.gov.in/eRctDeptInt/js/site.js?v=4q1jwFhaPaZgr8WAUSrux6hAuh0XDg9kPS3xIVq36I0"></script>
    <script src="~/modulejs/disablekeysdetail.js"></script>
</body>
</html>

Noc_App/Views/Grant/Index.cshtml
@model GrantViewModel
@{
    // ViewBag.Title = "Application of Grant for NOC Detail";
    // Layout = "~/Views/HomeLanding/_HomeLayout.cshtml";
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_LayoutSuccess.cshtml";
}
<h1> Congratulations!</h1>
@if (Model != null)
{
    <input hidden asp-for="Id" />
    <p>
        @if (Model.IsUnderMasterPlan)
        {
            @:Your application has been received successfully.
        }
        else
        {

            @if (Model.OrderId != "0")
            {
                @:Your application has been received successfully. <br />Payment of ₹@Model.TotalAmount has been received with transaction number @Model.OrderId
            }
            else
            {
                @:Your application has been received successfully, but payment is <b style="color:red">pending</b>.
                <br />
                @:Your application will be processed only after successful payment.
            }
        }
        <br /> Track its status with the following tracking number:<br />
        <b style="color:#76ac23">
            @Model.ApplicationID
        </b>
    </p>
    <p>
        <a asp-controller="Grant" asp-action="GeneratePdf" asp-route-Id="@Model.ApplicationID">Click here to view application</a>
    </p>
    <br />
    <p>
        <a class="btn btn-secondary btn-user btn-block" asp-controller="Grant" asp-action="Create">Back</a>
    </p>
}
else
{
    <p>Invalid request!</p>
}
@* <h1 style="text-align:center" class="h3 mb-4 text-gray-800">Application Detail</h1>
<div class="row">

    <div class="col-lg-12" style="text-align:center" >

        <!-- Circle Buttons -->
        <form class="user" method="post">
            <div class="card shadow mb-4">
                @if (Model != null)
                {
                    <input hidden asp-for="Id" />
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <tbody>
                            <tr><td>Your application has been received.</td></tr>
                        <tr>
                                <td>
                                    Track its status with the following tracking number: <b style="color:green">
                                        @Model.ApplicationID.
                                    </b>
                                </td>
                        </tr>
                    </tbody>
                    </table>
                }
                else
                {
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <tbody>
                            <tr>
                                <td>No Record Found</td>
                            </tr>
                        </tbody>
                    </table>
                }
            </div>
        </form>
    </div>
</div> *@

Noc_App/Views/Grant/Search.cshtml
@model GrantStatusViewModel;
@{
    ViewBag.Title = "Application Status";
    Layout = "~/Views/HomeLanding/_HomeLayout.cshtml";
}
<main id="main">
    <section id="contact" class="contact">
        <div class="container">

            <div class="section-title">
                <h2>Application Status</h2>
            </div>

            <div class="row">

                <div class="col-lg-12 mt-5 mt-lg-0 d-flex align-items-stretch">


                    <!-- Circle Buttons -->
                    <div class="php-email-form" id="grantForm">
                        <table class="table table-responsive table-striped table-bordered">
                            <tbody>
                                @if (Model != null)
                                {
                                    <tr>
                                        <td><b>Applicant ID</b></td>
                                        <td>@Model.ApplicationID</td>
                                    </tr>
                                    <tr>
                                        <td><b>Date of Application</b></td>
                                        <td>@Model.CreatedOn</td>
                                    </tr>

                                    @if (!Model.IsUnderMasterPlan)
                                    {
                                        <tr>
                                            <td><b>Payment</b></td>
                                            <td>@Model.ApplicationStatus</td>
                                        </tr>
                                        @if (Model.ApplicationStatus.ToLower() == "failed" || Model.ApplicationStatus.ToLower() == "pending")
                                        {
                                            <tr>
                                                <td><b>Action</b></td>
                                                <td>
                                                    <a class="text-center btn btn-success btn-user btn-block" asp-controller="Grant" asp-action="PayNow" asp-route-Id="@Model.ApplicationID">Pay Now</a>
                                                </td>
                                            </tr>

                                        }
                                        @if (Model.ApplicationStatus.ToLower() != "failed")
                                        {
                                            <tr>
                                                <td><b>Status</b></td>
                                                @if (Model.IsApproved)
                                                {
                                                    <td>
                                                        <a href="@Url.Action("Download", "Grant", new { fileName = Model.CertificateFilePath })">@Model.ApprovalStatus</a>
                                                    </td>
                                                }
                                                else
                                                {
                                                    <td>
                                                        @Model.ApprovalStatus
                                                    </td>
                                                }
                                            </tr>
                                        }
                                    }
                                    else
                                    {
                                        <tr>
                                            <td><b>Status</b></td>
                                            @if (Model.IsApproved)
                                            {
                                                <td>
                                                    <a href="@Url.Action("Download", "Grant", new { fileName = Model.CertificateFilePath })">@Model.ApprovalStatus</a>
                                                </td>
                                            }
                                            else
                                            {
                                                <td>
                                                    @Model.ApprovalStatus
                                                </td>
                                            }
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <td colspan="2"><span style="color:red;font-weight:bold;">No record found</span></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <center>
                        <a class="text-center btn btn-secondary btn-user btn-block" asp-controller="Grant" asp-action="TrackStatus">Back To Track Status</a>

                        </center>
                    </div>
                </div>

            </div>

        </div>
    </section>

</main>

@section Scripts {

}

Noc_App/Views/Grant/TrackStatus.cshtml
@{
    ViewBag.Title = "Track Application Status";
    Layout = "~/Views/HomeLanding/_HomeLayout.cshtml";
}
<main id="main">
    <section id="contact" class="contact">
        <div class="container">

            <div class="section-title">
                <h2>Track Application Status</h2>
                @* <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p> *@
            </div>

            <div class="row">

                <div class="col-lg-12 mt-5 mt-lg-0 d-flex align-items-stretch">


                    <!-- Circle Buttons -->
                    <form class="php-email-form" asp-action="Search" asp-controller="Grant" role="form" method="get" id="grantForm">

                        <div class="row">
                            <div class="form-group mt-3">
                                <label name="ApplicationID" class="control-label">Application ID</label>
                                <input name="searchString" placeholder="Search By Application ID" class="form-control form-control-user" />
                            </div>
                        </div>
                        <div class="row">
                            <div asp-validation-summary="All" class="text-danger validateAll"></div>
                        </div>
                        <div class="text-center"><button type="submit" class="btn btn-success btn-user btn-block">Search</button></div>


                    </form>
                </div>

            </div>

        </div>
    </section>

</main>

@section Scripts {

}

Noc_App/Views/Grant/UnAuthorized.cshtml
@{
    ViewData["Title"] = "Un-authorized....";
    Layout = "~/Views/Shared/_LayoutWithoutLinks.cshtml";
}



<div class="section-title">
    <h2>Un-Authorized Access</h2>
</div>

<div class="row">

    <div class="col-lg-12 mt-5 mt-lg-0 d-flex align-items-stretch">
        <div class="card shadow mb-4 col-lg-12">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card-header py-3">
                        <h2 class="m-0 font-weight-bold text-danger">Un-Authorized Access....</h2>
                    </div>
                    <div class="card-body">
                        <div class="row col-md-12">
                            <strong>
                                <label name="message" class="control-label">You are unauthorized to access this page</label>
                            </strong>
                            <div class="">
                                <div class="col-lg-12" style="text-align:center">
                                    <a class="btn btn-secondary btn-user btn-block" asp-controller="Grant" asp-action="Create">Home</a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

Noc_App/Views/Grant/UpdateIndex.cshtml
@model GrantViewModel
@{
    // ViewBag.Title = "Application of Grant for NOC Detail";
    // Layout = "~/Views/HomeLanding/_HomeLayout.cshtml";
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_LayoutSuccess.cshtml";
}
<h1> Congratulations!</h1>
@if (Model != null)
{
    <input hidden asp-for="Id" />
    <p>

            Your application has been updated successfully.
            
        
        <br /> Track its status with the following tracking number:<br />
        <b style="color:#76ac23">
            @Model.ApplicationID
        </b>
    </p>
    <p>
        <a asp-controller="Grant" asp-action="GeneratePdf" asp-route-Id="@Model.ApplicationID">Click here to view application</a>
    </p>
    <br />
    <p>
        <a class="btn btn-secondary btn-user btn-block" asp-controller="Grant" asp-action="Create">Back</a>
    </p>
}
else
{
    <p>Invalid request!</p>
}