Noc_App/Models/ViewModel/ProcessedApplicationsViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Noc_App.Models.ViewModel
{
    public class ProcessedApplicationsViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProjectTypeId { get; set; }
        public string OtherProjectTypeDetail { get; set; }
        public string Hadbast { get; set; }
        public string PlotNo { get; set; }
        public int VillageID { get; set; }
        public string ApplicantName { get; set; }
        [Display(Name = "Applicant Email")]
        public string ApplicantEmailID { get; set; }
        public int NocPermissionTypeID { get; set; }
        public int NocTypeId { get; set; }
        public string NocNumber { get; set; }
        public DateTime? PreviousDate { get; set; }
        public string ApplicationID { get; set; }
        public string VillageName { get; set; }
        public string LocationDetails { get; set; }
        public bool IsForwarded { get; set; }
        public bool isshortfall { get; set; }
        public bool isshortfallcompleted { get; set; }
        public bool ispending { get; set; }
        public bool isapproved { get; set; }
        public bool isrejected { get; set; }
        public bool IsShortFall { get; set; }
        public int ProcessedLevel { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CertificateFilePath { get; set; }
        public int IsRecommended { get; set; }
        public bool IsUnderMasterPlan { get; set; }
        public string ProcessedBy { get; set; }
        public string ProcessedByName { get; set; }
        public string ProcessedByRole { get; set; }
        public DateTime ProcessedOn { get; set; }
        public string ProcessedToUser { get; set; }
        public string ProcessedToName { get; set; }
        public string ProcessedToRole { get; set; }
        public string CurrentProcessedBy { get; set; }
        public string CurrentProcessedByName { get; set; }
        public string CurrentProcessedByRole { get; set; }
        public DateTime CurrentProcessedOn { get; set; }
        public string CurrentProcessedToUser { get; set; }
        public string CurrentProcessedToName { get; set; }
        public string CurrentProcessedToRole { get; set; }
    }
}

Noc_App/Models/ViewModel/TransferedApplicationsViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Noc_App.Models.ViewModel
{
    public class TransferedApplicationsViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProjectTypeId { get; set; }
        public string OtherProjectTypeDetail { get; set; }
        public string Hadbast { get; set; }
        public string PlotNo { get; set; }
        public int VillageID { get; set; }
        public string ApplicantName { get; set; }
        [Display(Name = "Applicant Email")]
        public string ApplicantEmailID { get; set; }
        public int NocPermissionTypeID { get; set; }
        public int NocTypeId { get; set; }
        public string NocNumber { get; set; }
        public DateTime? PreviousDate { get; set; }
        public string ApplicationID { get; set; }
        public string VillageName { get; set; }
        public string LocationDetails { get; set; }
        public bool IsForwarded { get; set; }
        public bool isshortfall { get; set; }
        public bool isshortfallcompleted { get; set; }
        public bool ispending { get; set; }
        public bool isapproved { get; set; }
        public bool isrejected { get; set; }
        public bool IsShortFall { get; set; }
        public int ProcessedLevel { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CertificateFilePath { get; set; }
        public int IsRecommended { get; set; }
        public bool IsUnderMasterPlan { get; set; }
        public string ProcessedBy { get; set; }
        public string ProcessedByName { get; set; }
        public string ProcessedByRole { get; set; }
        public DateTime ProcessedOn { get; set; }
        public string ProcessedToUser { get; set; }
        public string ProcessedToName { get; set; }
        public string ProcessedToRole { get; set; }
        public string CurrentProcessedBy { get; set; }
        public string CurrentProcessedByName { get; set; }
        public string CurrentProcessedByRole { get; set; }
        public DateTime CurrentProcessedOn { get; set; }
        public string CurrentProcessedToUser { get; set; }
        public string CurrentProcessedToName { get; set; }
        public string CurrentProcessedToRole { get; set; }
        public string tolocationname { get; set; }
    }
}

Noc_App/Controllers/ApprovalProcessController.cs
using Microsoft.AspNetCore.Mvc;
using Noc_App.Models.interfaces;
using Noc_App.Models;
using System.Runtime.CompilerServices;
using Noc_App.Models.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using Microsoft.AspNetCore.SignalR;
using Rotativa.AspNetCore;
using Noc_App.UtilityService;
using Noc_App.Helpers;
using System.Threading.Tasks.Dataflow;
using System.Data;
using Microsoft.EntityFrameworkCore;
using System.Text;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Authorization;
using System.Collections.Generic;
using System.Diagnostics.Eventing.Reader;

namespace Noc_App.Controllers
{
    public class ApprovalProcessController :Controller
    {
        private readonly IRepository<GrantDetails> _repo;
        //private readonly IRepository<VillageDetails> _villageRpo;
        private readonly IRepository<TehsilBlockDetails> _tehsilBlockRepo;
        private readonly IRepository<SubDivisionDetails> _subDivisionRepo;
        private readonly IRepository<DivisionDetails> _divisionRepo;
        //private readonly IRepository<UserDivision> _userDivisionRepository;
        //private readonly IRepository<UserSubdivision> _userSubDivisionRepository;
        //private readonly IRepository<UserVillage> _userVillageRepository;
        private readonly IRepository<GrantPaymentDetails> _repoPayment;
        private readonly IRepository<GrantApprovalDetail> _repoApprovalDetail;
        private readonly IRepository<GrantApprovalMaster> _repoApprovalMaster;
        private readonly IRepository<GrantApprovalProcessDocumentsDetails> _repoApprovalDocument;
        private readonly IRepository<ProjectTypeDetails> _projectTypeRepo;
        private readonly IRepository<NocPermissionTypeDetails> _nocPermissionTypeRepo;
        private readonly IRepository<NocTypeDetails> _nocTypeRepo;
        private readonly IRepository<OwnerTypeDetails> _ownerTypeRepo;
        private readonly IRepository<GrantKhasraDetails> _khasraRepo;
        private readonly IRepository<SiteAreaUnitDetails> _siteUnitsRepo;
        private readonly IRepository<GrantPaymentDetails> _grantPaymentRepo;
        private readonly IRepository<OwnerDetails> _grantOwnersRepo;
        private readonly IRepository<GrantUnprocessedAppDetails> _grantUnprocessedAppDetailsRepo;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IEmailService _emailService;
        private readonly ICalculations _calculations;
        private readonly IRepository<SiteUnitMaster> _repoSiteUnitMaster;
        private readonly IRepository<RecommendationDetail> _repoRecommendation;
        private readonly IRepository<UserRoleDetails> _userRolesRepository;
        private readonly IRepository<GrantSectionsDetails> _grantsectionRepository;
        private readonly IRepository<GrantRejectionShortfallSection> _grantrejectionRepository;
        private readonly IRepository<PlanSanctionAuthorityMaster> _repoPlanSanctionAuthtoryMaster;
        private readonly IRepository<DrainWidthTypeDetails> _drainwidthRepository;
        private readonly IRepository<GrantFileTransferDetails> _grantFileTransferRepository;
        private readonly IRepository<MasterPlanDetails> _masterPlanDetailsRepository;
        private readonly IRepository<CircleDivisionMapping> _circleDivRepository;
        private readonly IRepository<EstablishmentOfficeDetails> _establishOffRepository;
        private readonly IRepository<ProcessedApplicationsViewModel> _processedAppDetailsRepo;
        private readonly IRepository<TransferedApplicationsViewModel> _transferedAppDetailsRepo;
        private readonly IConfiguration _configuration;
        private readonly IRepository<GrantPendingApplicationDetails> _grantPendingApplicationDetailsRepo;


        public ApprovalProcessController(IRepository<GrantDetails> repo, /*IRepository<VillageDetails> villageRepo,*/ IRepository<TehsilBlockDetails> tehsilBlockRepo, IRepository<SubDivisionDetails> subDivisionRepo,
            IRepository<DivisionDetails> divisionRepo, IRepository<GrantPaymentDetails> repoPayment,IRepository<GrantApprovalDetail> repoApprovalDetail, IRepository<GrantApprovalMaster> repoApprovalMaster
            , IRepository<ProjectTypeDetails> projectTypeRepo, IRepository<NocPermissionTypeDetails> nocPermissionTypeRepo, IRepository<MasterPlanDetails> masterPlanDetailsRepository,
            IRepository<NocTypeDetails> nocTypeRepo, IRepository<OwnerTypeDetails> ownerTypeRepo, IRepository<GrantPaymentDetails> grantPaymentRepo, IRepository<OwnerDetails> grantOwnersRepo,
            IRepository<GrantKhasraDetails> khasraRepo, IRepository<SiteAreaUnitDetails> siteUnitsRepo, IWebHostEnvironment hostingEnvironment, IEmailService emailService
            , IRepository<GrantApprovalProcessDocumentsDetails> repoApprovalDocument,IRepository<GrantUnprocessedAppDetails> grantUnprocessedAppDetailsRepo
            , ICalculations calculations, IRepository<SiteUnitMaster> repoSiteUnitMaster, IRepository<RecommendationDetail> repoRecommendation, IRepository<GrantPendingApplicationDetails> grantPendingApplicationDetailsRepo
            , IRepository<UserRoleDetails> userRolesRepository, IRepository<GrantSectionsDetails> grantsectionRepository, IRepository<DrainWidthTypeDetails> drainwidthRepository
            , IRepository<GrantRejectionShortfallSection> grantrejectionRepository, IRepository<PlanSanctionAuthorityMaster> repoPlanSanctionAuthtoryMaster
            , IRepository<GrantFileTransferDetails> grantFileTransferRepository, IRepository<CircleDivisionMapping> circleDivRepository, IRepository<TransferedApplicationsViewModel> transferedAppDetailsRepo
            , IRepository<EstablishmentOfficeDetails> establishOffRepository, IRepository<ProcessedApplicationsViewModel> processedAppDetailsRepo, IConfiguration configuration)
        {
            _repo = repo;
            //_villageRpo = villageRepo;
            _tehsilBlockRepo = tehsilBlockRepo;
            _subDivisionRepo = subDivisionRepo;
            _divisionRepo = divisionRepo;
            _repoPayment = repoPayment;
            _repoApprovalDetail = repoApprovalDetail;
            _repoApprovalMaster = repoApprovalMaster;
            _hostingEnvironment = hostingEnvironment;
            _projectTypeRepo = projectTypeRepo;
            _nocPermissionTypeRepo = nocPermissionTypeRepo;
            _nocTypeRepo = nocTypeRepo;
            _ownerTypeRepo = ownerTypeRepo;
            _khasraRepo = khasraRepo;
            _siteUnitsRepo = siteUnitsRepo;
            _grantPaymentRepo = grantPaymentRepo;
            _grantOwnersRepo = grantOwnersRepo;
            _emailService = emailService;
            _repoApprovalDocument = repoApprovalDocument;
            _grantUnprocessedAppDetailsRepo = grantUnprocessedAppDetailsRepo;
            _calculations = calculations;
            _repoSiteUnitMaster = repoSiteUnitMaster;
            _repoRecommendation = repoRecommendation;
            _userRolesRepository = userRolesRepository;
            _grantsectionRepository = grantsectionRepository;
            _drainwidthRepository = drainwidthRepository;
            _grantrejectionRepository = grantrejectionRepository;
            _repoPlanSanctionAuthtoryMaster = repoPlanSanctionAuthtoryMaster;
            _grantFileTransferRepository= grantFileTransferRepository;
            _masterPlanDetailsRepository=masterPlanDetailsRepository;
            _circleDivRepository = circleDivRepository;
            _establishOffRepository = establishOffRepository;
            _processedAppDetailsRepo = processedAppDetailsRepo;
            _transferedAppDetailsRepo = transferedAppDetailsRepo;
            _configuration = configuration;
            _grantPendingApplicationDetailsRepo = grantPendingApplicationDetailsRepo;
        }

        [Authorize(Roles = "PRINCIPAL SECRETARY,MINISTER,EXECUTIVE ENGINEER,CIRCLE OFFICER,CHIEF ENGINEER DRAINAGE,DWS,EXECUTIVE ENGINEER DRAINAGE,JUNIOR ENGINEER,SUB DIVISIONAL OFFICER,ADE,DIRECTOR DRAINAGE")]
        public async Task<ViewResult> Index()
        {
            try
            {

                string userId = "0";// LoggedInUserID();

                    string divisionId = LoggedInDivisionID();
                
                // Retrieve roles associated with the user
                var roleName = LoggedInRoleName();
                string role = roleName;
                role = (await GetAppRoleName(role)).AppRoleName;
                List<List<GrantPendingApplicationDetails>> modelView = new List<List<GrantPendingApplicationDetails>>();
                List<GrantPendingApplicationDetails> model = new List<GrantPendingApplicationDetails>();
                if (role == "PRINCIPAL SECRETARY" || role == "MINISTER" || role == "CHIEF ENGINEER DRAINAGE" || role== "EXECUTIVE ENGINEER DRAINAGE" || role== "DIRECTOR DRAINAGE" || role== "DWS" || role== "ADE")
                    divisionId = "0";
                model =await _grantPendingApplicationDetailsRepo.ExecuteStoredProcedureAsync<GrantPendingApplicationDetails>("getapplicationstoforward", "0", "0", "0", "0", divisionId, "'" +role+"'", "'" + userId + "'");
                var modelForwarded = await _grantPendingApplicationDetailsRepo.ExecuteStoredProcedureAsync<GrantPendingApplicationDetails>("getapplicationsforwarded", "0", "0", "0", "0", divisionId, "'" + role + "'", "'" + userId + "'");
                var modelRejected = await _grantPendingApplicationDetailsRepo.ExecuteStoredProcedureAsync<GrantPendingApplicationDetails>("getapplicationsrejected", "0", "0", "0", "0", divisionId, "'" + role + "'", "'" + userId + "'");
                var modelIssued = await _grantPendingApplicationDetailsRepo.ExecuteStoredProcedureAsync<GrantPendingApplicationDetails>("getapplicationsissued", "0", "0", "0", "0", divisionId, "'" + role + "'", "'" + userId + "'");

Noc_App/Views/ApprovalProcess/IssueNOC.cshtml
@model IssueNocViewModelCreate
@{
    ViewBag.Title = Model.IsSiteWithin150m ? "Issue NOC" : "Upload Exemption Letter";
}
@if (Model.IsSiteWithin150m)
{
    <h1 class="h3 mb-4 text-gray-800">Issue NOC</h1>
}
else
{
    <h1 class="h3 mb-4 text-gray-800">Upload Exemption Letter</h1>
}

<div class="row">

    <div class="col-lg-12">

        <!-- Circle Buttons -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                @if (Model.IsSiteWithin150m)
                {
                    <h6 class="m-0 font-weight-bold text-primary">Issue NOC</h6>
                }
                else
                {
                    <h6 class="m-0 font-weight-bold text-primary">Upload Exemption Letter</h6>
                }
            </div>
            <div class="card-body">
                <form class="user" enctype="multipart/form-data" asp-action="IssueNOC" method="post">
                    <input type="hidden" asp-for="Id" />
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <input type="hidden" asp-for="IsUnderMasterPlan" />
                                <label asp-for="Name" class="control-label">Project</label>
                                <input asp-for="Name" readonly class="form-control form-control-user" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label asp-for="ApplicationID" class="control-label">Application Id</label>
                                <input asp-for="ApplicationID" readonly class="form-control form-control-user" />
                                <span asp-validation-for="ApplicationID" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label asp-for="LocationDetails" class="control-label">Location</label>
                                <input asp-for="LocationDetails" readonly class="form-control form-control-user" />
                                <span asp-validation-for="LocationDetails" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">

                        @if (Model.IsPartiallyApproved)
                        {
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label asp-for="PreviousRemarks" class="control-label">Remarks By @Model.PreviosAuthorityRole </label>
                                    <textarea asp-for="PreviousRemarks" readonly placeholder="PreviousRemarks" class="form-control" cols="3" rows="2"></textarea>
                                    <span asp-validation-for="PreviousRemarks" class="text-danger"></span>
                                </div>
                            </div>
                        }
                        <div class="col-lg-4">
                            <div class="form-group">
                                @if (Model.IsSiteWithin150m)
                                {
                                    <label asp-for="CertificateFile" class="control-label">Upload NOC</label>
                                }else{
                                    <label asp-for="CertificateFile" class="control-label">Upload Exemption Letter</label>
                                }
                                <span style="color:red"> (Max File (pdf) Size 4MB)</span>
                                <div class="custom-file1">
                                    <input asp-for="CertificateFile" class="form-control custom-file-input1" accept=".pdf" />
                                    @* <label class="custom-file-label1">Choose File...</label> *@
                                    <span asp-validation-for="CertificateFile" id="SiteConditionReportFile-error" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="row">
                        <div class="col-lg-6">
                            @if (Model.IsSiteWithin150m)
                            {
                                <button type="submit" class="btn btn-primary btn-user btn-block">Issue</button>
                            }
                            else{
                                <button type="submit" class="btn btn-primary btn-user btn-block">Upload</button>
                            }
                            </div>
                        <div class="col-lg-6">
                            <a class="btn btn-secondary btn-user btn-block" asp-controller="ApprovalProcess" asp-action="Index">Back To List</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>



</div>

Noc_App/Views/ApprovalProcess/PartiallyApproveNOC.cshtml
@model PartiallyApproveViewModelCreate
@{
    ViewBag.Title = Model.IsUnderMasterPlan ? "Approve NOC" : "Approve NOC";
}
@* @if (Model.IsUnderMasterPlan)
{ *@
<h1 class="h3 mb-4 text-gray-800">Approve NOC</h1>
@* }
else
{
    <h1 class="h3 mb-4 text-gray-800">Issue NOC</h1>
} *@

<div class="row">

    <div class="col-lg-12">

        <!-- Circle Buttons -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                @* @if (Model.IsUnderMasterPlan)
                { *@
                    <h6 class="m-0 font-weight-bold text-primary">Approve NOC</h6>
                @* }
                else
                {
                    <h6 class="m-0 font-weight-bold text-primary">Issue NOC</h6>
                } *@
            </div>
            <div class="card-body">
                <form class="user" asp-action="PartiallyApproveNOC" method="post">
                    <input type="hidden" asp-for="Id" />
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="form-group">
                                <input asp-for="ForwardToRole" type="hidden" id="ForwardToRole" />
                                <input asp-for="ToLocationId" type="hidden" id="ToLocationId" />
                                <input asp-for="FromLocationId" type="hidden" id="FromLocationId" />
                                <input asp-for="LoggedInRole" type="hidden" id="userRole" />
                                <input type="hidden" id="pageName" value="F" />
                                <input type="hidden" asp-for="IsUnderMasterPlan" />
                                <label asp-for="Name" class="control-label">Project</label>
                                <input asp-for="Name" readonly class="form-control form-control-user" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label asp-for="ApplicationID" class="control-label">Application Id</label>
                                <input asp-for="ApplicationID" readonly class="form-control form-control-user" />
                                <span asp-validation-for="ApplicationID" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label asp-for="LocationDetails" class="control-label">Location</label>
                                <input asp-for="LocationDetails" readonly class="form-control form-control-user" />
                                <span asp-validation-for="LocationDetails" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">

                        <div class="col-lg-3">
                            <div class="form-group">
                                <label asp-for="SelectedOfficerId" class="control-label">Document Uploaded By</label>
                                @if (Model.Officers != null)
                                {
                                    @if (Model.Officers.Count() > 0)
                                    {
                                        <select asp-for="SelectedOfficerId" id="SelectedOfficerId" asp-items="@Model.Officers" class="form-control">
                                            <option value="">Select</option>
                                        </select>
                                    }
                                    else
                                    {
                                        <select name="SelectedOfficerId" disabled id="SelectedOfficerId" class="form-control">
                                            <option value="">No Officer</option>
                                        </select>
                                    }

                                }
                                else
                                {
                                    <select name="SelectedOfficerId" id="SelectedOfficerId" disabled class="form-control">
                                        <option value="">No Officer</option>
                                    </select>
                                }
                                <span asp-validation-for="SelectedOfficerId" id="SelectedOfficerIdVal" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label asp-for="SelectedDivisionId" class="control-label">Location</label>
                                @if (Model.Divisions != null)
                                {
                                    @if (Model.Divisions.Count() > 0)
                                    {
                                        <select asp-for="SelectedDivisionId" id="SelectedDivisionId" asp-items="@Model.Divisions" class="form-control">
                                            <option value="">Select</option>
                                        </select>
                                    }
                                    else
                                    {
                                        <select name="SelectedDivisionId" id="SelectedDivisionId" disabled class="form-control">
                                            <option value="">Select</option>
                                        </select>
                                    }
                                }
                                else
                                {
                                    <select name="SelectedDivisionId" id="SelectedDivisionId" disabled class="form-control">
                                        <option value="">Select</option>
                                    </select>
                                }
                                <span asp-validation-for="SelectedDivisionId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label asp-for="Remarks" class="control-label"></label>
                                <textarea asp-for="Remarks" placeholder="Remarks" class="form-control" cols="3" rows="2"></textarea>
                                <span asp-validation-for="Remarks" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="row">
                        @if (Model.Officers != null && Model.Officers.Count() > 0)
                        {
                            @if (Model.Divisions != null && Model.Divisions.Count() > 0)
                            {
                                <div class="col-lg-6">

                                    <button type="submit" class="btn btn-primary btn-user btn-block">Approve</button>
                                </div>
                                <div class="col-lg-6">
                                    <a class="btn btn-secondary btn-user btn-block" asp-controller="ApprovalProcess" asp-action="Index">Back To List</a>
                                </div>
                            }
                            else
                            {
                                <div class="col-lg-6">

                                    <button type="submit" disabled id="btnForward" class="btn btn-primary btn-user btn-block">Approve</button>
                                </div>
                                <div class="col-lg-6">
                                    <a class="btn btn-secondary btn-user btn-block" asp-controller="ApprovalProcess" asp-action="Index">Back To List</a>
                                </div>
                            }
                        }
                        else
                        {
                            <div class="col-lg-6 offset-lg-3">
                                <a class="btn btn-secondary btn-user btn-block" asp-controller="ApprovalProcess" asp-action="Index">Back To List</a>
                            </div>
                        }
                        
                    </div>
                </form>
            </div>
        </div>

    </div>



</div>

@section Scripts {
    <script src="~/modulejs/appforwardscript.js"></script>
}

Noc_App/Views/ApprovalProcess/Reject.cshtml
@model GrantApprovalDetailReject
@{
    ViewBag.Title = "Reject Application";
}

<h1 class="h3 mb-4 text-gray-800">Reject Application</h1>

<div class="row">

    <div class="col-lg-6">

        <!-- Circle Buttons -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Are you sure you want to reject?</h6>
            </div>
            <div class="card-body">
                <form class="user" enctype="multipart/form-data" asp-action="Reject" method="post">
                    <input type="hidden" asp-for="id" />
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label asp-for="Remarks" class="control-label"></label><strong> (The same remarks shall be shared with the applicant)</strong>
                                <textarea asp-for="Remarks" class="form-control form-control-user" ></textarea>
                                <span asp-validation-for="Remarks" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="row">
                        <div class="col-lg-6">

                            <button type="submit" class="btn btn-danger btn-user btn-block" onclick="return confirm('Are you sure you want to reject?')" >Reject</button>
                        </div>
                        <div class="col-lg-6">
                            <a class="btn btn-secondary btn-user btn-block" asp-controller="ApprovalProcess" asp-action="Index">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>



</div>